project_id = "zyaoilcrfxqhmkrmrqfd"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54320
site_url = "https://zyaoilcrfxqhmkrmrqfd.supabase.co"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false

[functions.ai-chat]
verify_jwt = false